baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '念西堂'
theme = 'pacman'


[Author]
  Name = "任怀林"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
[Params]
  AuthorHomepage = "/about"
  Author = "任怀林"
  #BottomIntroduce = "念西堂 <br/> 阿弥陀佛"
  Description = ""
  Subtitle = "一个热爱写程序的平凡人的博客"
  Weibo = ""
  WeiboID = 123
  Twitter = ""
  GitHub = ""
  Facebook = ""
  LinkIn = ""
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  CreativeCommons = true
  MathJax = false

  [Params.GoogleAnalytics]
    ID = "G-21F3GS6PC0"
    gtag_ID = "G-21F3GS6PC0"

  [Params.Disqus]
    ShortName = ""

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

  [Params.comments.giscus]
    repo = "renhuailin/renhuailin.github.io"
    repoID = "R_kgDOIuU-oQ"
    category = "Announcements"
    categoryID = "DIC_kwDOIuU-oc4CTa92"
    mapping = "pathname"
    dataStrict = "0"
    reactionsEnabled = "1"
    lang = "zh-CN"
    lazy = "lazy"
[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2